### ISSUE TITLE
Implement all status discount types

### ISSUE THREAD

**Issue by linusnorton** [open-track/fares-service#1]
The Status class has a `discountIndicator` field that is described on page 43 of RSPS5045. At present on only type 0 is implemented. Implement the rest with tests in `StatusTest.php`
##

**Comment by matiangul** [comment]
Is there some way to change it somehow to "in-progress"?

**Comment by linusnorton** [comment]
@matiangul it turned out this can be closed. I have a lot of work that I didn't push on this repo so I'll do that.

The project board is here https://github.com/open-track/traintickets.to/projects/1
